### ISSUE TITLE
Add HTTP support

### ISSUE THREAD

**Issue by clementblaise** [rockstorm101/git-server-docker#1]
First thanks for making this, it's the only one that works on ARM and simple to configure.

It would be even better with the option to expose over HTTP in addition to SSH.

**Comment by rockstorm101** [comment]
Hi! Glad you find it useful! I will look into web support, I can see that being convenient for some users. It won't be a fancy web interface though.

**Comment by clementblaise** [comment]
Great thanks ! Yeah I totally agree no need for a fancy UI, just the ability to pull over HTTP.

**Comment by janjoost-denbrinker** [comment]
I'd gladly put the web interface together!

**Comment by rockstorm101** [comment]
It seems a dedicated webserver is always required to either:

 1. Being able to pull/push through HTTP
 2. Visualize the repositories with something like [GitWeb][1]
 
In my mind, anyone wanting these features should run a webserver alongside this image instead of us including the webserver. This way the user is free to choose the webserver of their preference (say Apache, Nginx, lighthttpd,...) instead of us enforcing one, he can configure it however secure and efficient he likes and he can even change it without affecting the SSH server. Essentially, stick to the "one service per container" philosophy (ultimately the "Do One Thing and Do It Well") as much as possible.

This being said, an image such as Kostya's [gitweb-readonly][2] could be run to visualize the repositories. One would just need to ensure both services share the location/volume with the repositories like:

```
services:
  git-server:
    image: rockstorm/git-server
    ...
    volumes:
      - ./path/to/repos:/srv/git
	  
  gitweb:
    image: kostyaesmukov/gitweb-readonly
    ...
    volumes:
      - ./path/to/repos:/var/lib/git:ro
```

Unfortunately that image is only available for the 'amd64' architecture. I might look into providing a lightweight ARM-capable image for gitweb that could be used in a similar manner. If you know any other gitweb or http-server useful images please let me know. It'd be great to include them in the README for reference.

All in all, I would leave the issue open for future reference but tag it as "won't fix". Leaving the HTTP support to be dealt with in another repository. Let me know what you think.

[1]: https://git-scm.com/book/en/v2/Git-on-the-Server-GitWeb
[2]: https://hub.docker.com/r/kostyaesmukov/gitweb-readonly

**Comment by rockstorm101** [comment]
I went ahead and [packaged GitWeb][1] to run along this image. Hope it helps, any feedback will be appreciated.

[1]: https://github.com/rockstorm101/gitweb-docker
