### ISSUE TITLE
do NOT reuse tags!

### ISSUE THREAD

**Issue by fragolinux** [rockstorm101/git-server-docker#5]
PLEASE, avoid _reusing_ tags when committing to git...

previous SHA256: sha256:b8e5d2e47be174544b823b172b3d61356286bae878e6608abc45b3b32ce2ee4d
actual SHA256: sha256:749b66e8c314c330c44f44fe8aae2e12292128389e5edc324f254548604b262f

or viceversa, btw both pointed by the same tag, 2.36, which just breaks things if you save on a gitops repo the ssh host keys, for example to easily use flux on a local cluster pointing to a local git server... tags must be immutable!

**Comment by rockstorm101** [comment]
Noted. I wasn't aware of this inconvenience, thank you for pointing that out. Won't be re-purposing tags from now on. Time to revisit the docker image tags as well.

**Comment by fragolinux** [comment]
> Noted. I wasn't aware of this inconvenience, thank you for pointing that out. Won't be re-purposing tags from now on. Time to revisit the docker image tags as well.

well, right now this is not true... just checked and seen tag 2.38, pushed 2 hours ago... BUT, 2.38 was already existing DAYS ago, so you just threw it away and recycled it again... I understand your purpose, to align the "git" version with your tag, but, sorry to say, this is just messing around what a tag should be: a STATIC point in time to a specific commit or image...

PLEASE find an other way to deal with this...

**Comment by rockstorm101** [comment]
> > Noted. I wasn't aware of this inconvenience, thank you for pointing that out. Won't be re-purposing tags from now on. Time to revisit the docker image tags as well.
> 
> well, right now this is not true... just checked and seen tag 2.38, pushed 2 hours ago... BUT, 2.38 was already existing DAYS ago, so you just threw it away and recycled it again... I understand your purpose, to align the "git" version with your tag, but, sorry to say, this is just messing around what a tag should be: a STATIC point in time to a specific commit or image...
> 
> PLEASE find an other way to deal with this...

Hi @fragolinux, first, thank you for taking the time to give feedback on this. Maybe I didn't understand you on your first post and I've probably done a poor job explaining what I'm doing.

I thought the problem was reusing _git_ tags (not _docker_ tags). Which is now achieved by the use of the of the `+bX` suffix. A few days ago tag '2.38+b1' was used and we are at at '2.38+b2'. That's it for the git repository. No plain `2.38` tag anymore.

On the other hand, Docker tags function slightly different. I've tried explaining this on the [Tagging Scheme][1] section on the README. Three kinds of Docker tags:
 - Inmutable tags: the ones with `+bX` suffix which correspond to the same tag on the git repository. These tags won't be reused. Build number will be incremented every time the image is built. I hope this meets your needs and I see this being important for production stuff.
 - Stable tags: the ones like `2.38` with no suffix. These follow the latest build for the 2.38 tag. I believe these are useful for people willing to get the latest patches and fixes without having to keep changing their target image. Also useful if this image is used as a base image.
 - The 'latest' tag: which simply follows the very latest image no matter what.

Let me know if this scheme solves your issues or why it doesn't. Or if anybody else wants to add or suggest on this. I'm more than happy to contemplate any options. For reference, the reasons why I went with the above scheme are laid out on [Steve Lasker's post][2] on Docker tagging.

Thanks again.

[1]: https://github.com/rockstorm101/git-server-docker#tagging-scheme
[2]: https://stevelasker.blog/2018/03/01/docker-tagging-best-practices-for-tagging-and-versioning-docker-images/

**Comment by rockstorm101** [comment]
I consider this matter solved now so I'll close this issue. If the current [tagging scheme][1] still causes problems please do let me know. Thanks again for reporting this issue.

[1]: https://github.com/rockstorm101/git-server-docker#tagging-scheme
